[application]

# App (Project) Name
name = "wallet"

[web.app]

# HTML title tag content
title = "wallet"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "regolith labs"
identifier = "ore.supply"
